### ISSUE TITLE
Catch all doesn't work, neither does traces

### ISSUE THREAD

**Issue by MortInfinite** [hdurdle/RegExCatchAllAgent#1]
I have tried installing the RegExCatchAllAgent on my Exchange 2010, by following the documentation provided, but unfortunately without any success.

It seems that the transport agent is installed correctly, it appears in the list of transport agents, above the Recipient Filter Agent and it's enabled.

The config.xml file is configured with a regex filter identical to the john sample, except using my own domain and mail address instead. 

Unfortunately no mails are ever redirected to the mailbox specified and when the edgetransport.exe.config is setup to log events to the traces.txt log file, this log file isn't ever created.

Every time I made any changes or new attempts, I've been restarting the MSExchangeTransport service.

Any idea on how to troubleshoot this issue, without installing a development environment on the exchange server?

**Comment by hdurdle** [comment]
The published code must be compiled with references to the correct DLLs for your version of Exchange (down the correct service pack level).

Also, the agent won't trigger unless email is coming in from outside your network - sending mail using Internal clients will not trigger the agent.

**Comment by MortInfinite** [comment]
Thank you for the suggestion!

Removing and re-adding the project references to the Exchange assemblies I was using, made it work.
